import discord
from discord.ext import commands
import json
import os
import datetime
from cogs.core.pst_timezone import get_now_pst

DATA_FILE = 'data/auto_reports.json'

class AutoReportGeneratorCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    def load_reports(self):
        if os.path.exists(DATA_FILE):
            try:
                with open(DATA_FILE, 'r') as f:
                    return json.load(f)
            except:
                return self.get_default_data()
        return self.get_default_data()

    def save_reports(self, data):
        os.makedirs('data', exist_ok=True)
        with open(DATA_FILE, 'w') as f:
            json.dump(data, f, indent=4)

    def get_default_data(self):
        return {
            "reports": [],
            "scheduled_reports": [],
            "report_templates": [
                {"id": 1, "name": "Daily Security Summary", "frequency": "daily"},
                {"id": 2, "name": "Weekly Incident Report", "frequency": "weekly"},
                {"id": 3, "name": "Monthly Risk Assessment", "frequency": "monthly"}
            ]
        }

    async def is_staff(self, ctx):
        return ctx.author.id == int(os.getenv('BOT_OWNER_ID', '0')) or ctx.channel.permissions_for(ctx.author).manage_messages

    @commands.command(name='generate_report')
    async def generate_report(self, ctx, report_type: str, *, description: str):
        """Generate a security report"""
        if not await self.is_staff(ctx):
            await ctx.send("❌ Only staff can generate reports.")
            return
        
        data = self.load_reports()
        report_id = len(data["reports"]) + 1
        
        report = {
            "id": report_id,
            "type": report_type,
            "description": description,
            "generated_at": datetime.get_now_pst().isoformat(),
            "generated_by": str(ctx.author),
            "status": "completed",
            "sections": []
        }
        
        data["reports"].append(report)
        self.save_reports(data)
        
        embed = discord.Embed(title="✅ Report Generated", color=discord.Color.green())
        embed.add_field(name="Report ID", value=f"RPT-{report['id']}", inline=True)
        embed.add_field(name="Type", value=report_type, inline=True)
        embed.add_field(name="Description", value=description, inline=False)
        await ctx.send(embed=embed)

    @commands.command(name='schedule_report')
    async def schedule_report(self, ctx, report_type: str, frequency: str, *, template: str):
        """Schedule a recurring report"""
        if not await self.is_staff(ctx):
            await ctx.send("❌ Only staff can schedule reports.")
            return
        
        data = self.load_reports()
        
        scheduled = {
            "id": len(data["scheduled_reports"]) + 1,
            "type": report_type,
            "frequency": frequency,
            "template": template,
            "scheduled_at": datetime.get_now_pst().isoformat(),
            "scheduled_by": str(ctx.author),
            "active": True,
            "next_run": datetime.get_now_pst().isoformat()
        }
        
        data["scheduled_reports"].append(scheduled)
        self.save_reports(data)
        
        await ctx.send(f"✅ Report scheduled: {report_type} ({frequency})")

    @commands.command(name='report_detail')
    async def report_detail(self, ctx, report_id: int):
        """View detailed report information"""
        data = self.load_reports()
        report = next((r for r in data["reports"] if r["id"] == report_id), None)
        
        if not report:
            await ctx.send(f"❌ Report RPT-{report_id} not found.")
            return
        
        embed = discord.Embed(title=f"Report RPT-{report_id}", color=discord.Color.blue())
        embed.add_field(name="Type", value=report["type"], inline=True)
        embed.add_field(name="Status", value=report["status"], inline=True)
        embed.add_field(name="Generated", value=report["generated_at"][:10], inline=True)
        embed.add_field(name="Generated By", value=report["generated_by"], inline=True)
        embed.add_field(name="Description", value=report["description"], inline=False)
        embed.add_field(name="Sections", value=len(report["sections"]), inline=True)
        
        await ctx.send(embed=embed)

    @commands.command(name='list_reports')
    async def list_reports(self, ctx, limit: int = 10):
        """List recent reports"""
        data = self.load_reports()
        
        if not data["reports"]:
            await ctx.send("No reports generated yet.")
            return
        
        embed = discord.Embed(title="📊 Recent Reports", color=discord.Color.blue())
        
        for report in data["reports"][-limit:]:
            embed.add_field(
                name=f"RPT-{report['id']}: {report['type']}",
                value=f"Generated: {report['generated_at'][:10]}\nStatus: {report['status']}",
                inline=False
            )
        
        await ctx.send(embed=embed)

    @commands.command(name='report_templates')
    async def report_templates(self, ctx):
        """View available report templates"""
        data = self.load_reports()
        
        embed = discord.Embed(title="📋 Report Templates", color=discord.Color.blue())
        
        for template in data["report_templates"]:
            embed.add_field(
                name=template["name"],
                value=f"Frequency: {template['frequency']}",
                inline=False
            )
        
        await ctx.send(embed=embed)

async def setup(bot):
    await bot.add_cog(AutoReportGeneratorCog(bot))
